//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Ahorro
    {
        public long id { get; set; }
        public int idCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Valor { get; set; }
        [JsonIgnore]

        public virtual Cliente Cliente { get; set; }
    }
}
