//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NatilleraDBEntities : DbContext
    {
        public NatilleraDBEntities()
            : base("name=NatilleraDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Ahorro> Ahorroes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Evento> Eventoes { get; set; }
        public virtual DbSet<Evento_Lugar> Evento_Lugar { get; set; }
        public virtual DbSet<Liquidacion> Liquidacions { get; set; }
        public virtual DbSet<Lugar> Lugars { get; set; }
        public virtual DbSet<Perfil> Perfils { get; set; }
        public virtual DbSet<Prestamo> Prestamoes { get; set; }
        public virtual DbSet<Proveedor> Proveedors { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Usuario_perfil> Usuario_perfil { get; set; }
    }
}
