//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Evento_Lugar
    {
        public int idEvento { get; set; }
        public int idLugar { get; set; }
        public int HorasAlquiler { get; set; }
        [JsonIgnore]

        public virtual Evento Evento { get; set; }
        [JsonIgnore]
        public virtual Lugar Lugar { get; set; }
    }
}
