//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento_Lugar
    {
        public int idEvento { get; set; }
        public int idLugar { get; set; }
        public int HorasAlquiler { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Lugar Lugar { get; set; }
    }
}
