//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public long id { get; set; }
        public long idPrestamo { get; set; }
        public System.DateTime FechaLiquidacion { get; set; }
        public decimal MontoTotal { get; set; }
        public decimal Intereses { get; set; }
    
        public virtual Prestamo Prestamo { get; set; }
    }
}
