//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Natillera.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_perfil
    {
        public long id { get; set; }
        public long idUsuario { get; set; }
        public long idPerfil { get; set; }
        public bool Activo { get; set; }
        [JsonIgnore]

        public virtual Perfil Perfil { get; set; }
        [JsonIgnore]
        public virtual Usuario Usuario { get; set; }
    }
}
